### PR TITLE
Delete data-files destination dirs before copying

### LINKED ISSUE #33: "file exists" error if folder is added to data-files
The README points out, _that that copying entire directories is supported_ for data files. 

If I use something like this:
```
[tool.colcon-poetry-ros.data-files]
"share/ament_index/resource_index/packages" = ["resource/{package_name}"]
"share/{package_name}" = ["package.xml", "secrets"]
```
The first build runs fine and _secrets_ folder is copied to share folder correctly. But from the second build on, I do get the following error:
```
--- stderr: {package_name}                   
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/colcon_poetry_ros/task/poetry/build.py", line 133, in build
    return_code = await self._add_data_files()
  File "/usr/local/lib/python3.8/dist-packages/colcon_poetry_ros/task/poetry/build.py", line 209, in _add_data_files
    shutil.copytree(str(source_path), str(dest_path / source_path.name))
  File "/usr/lib/python3.8/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.8/shutil.py", line 458, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/path/to/my/ros2/ws/install/{package_name}/share/{package_name}/secrets'
```
Thanks in advance, regards, Nils

### PR DESCRIPTION
**Pull request by velovix**
Fixes #33

### CODE REVIEW

**Review by apockill — APPROVED** [review]
Why does this problem not happen to us? Is it because we're using docker, so we always run colcon-poetry in a clean environment

**Comment by velovix** [comment]
Yes! That's exactly why.

**Comment by velovix** [comment]
@nilskuhn Would you mind trying this to see if it solves your problem? I was able to replicate and resolve the issue on my end but I'd like to make sure I'm not missing anything.

You can install the version from this PR with this command:

```bash
pip3 install git+https://github.com/UrbanMachine/colcon-poetry-ros.git@ed14d26e4490457f08ed072f39d9e7864ab3912f
```

**Comment by nilskuhn** [comment]
yes, that works for my case. Thanks a lot, that was a quick fix! 
Which version will contain this fix and do you have a rough plan when you will be able to package and publish that one?

**Comment by velovix** [comment]
Glad to hear it! I'll make a new patch release with this fix right now.

**Pull request merged**
