### PR TITLE
WIP: Ensure pip install paths are under "site-packages"

### PR DESCRIPTION
**Pull request by nznobody**
In my environment pip was installing under `local` and `dist-packages`. This appears to be standard behavior, but not what ROS expects.

Resolve this by moving the packages.

My system (docker):
```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

$ python3 -m pip --version
pip 22.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
```

### CODE REVIEW

**Comment by nznobody** [comment]
Also resolves hashes required

**Comment by nznobody** [comment]
The plot thickens. Damn Debian has really cooked it now. The mixing of `local` and `dist-packages` has wasted my entire day :(

Sadly when you use poetry to generate the `requirements.txt` and then pip install it, they also go to local and dist-packages. I am wondering how deep I should go....

**Comment by velovix** [comment]
Hmm, perhaps this hasn't come up for us because we use a newer version of Pip from the one included in Ubuntu. We're also currently using 20.04. It doesn't make very much sense to me that Pip installs to `dist-packages`, though. I thought that directory was for Python libraries installed through apt, not Pip.

Does the behavior change if you upgrade Pip?

```bash
pip3 install --upgrade pip
```

**Comment by velovix** [comment]
Also, what lead you to disable hashes?

**Comment by nznobody** [comment]
> Hmm, perhaps this hasn't come up for us because we use a newer version of Pip from the one included in Ubuntu. We're also currently using 20.04. It doesn't make very much sense to me that Pip installs to `dist-packages`, though. I thought that directory was for Python libraries installed through apt, not Pip.
> 
> Does the behavior change if you upgrade Pip?
> 
> ```shell
> pip3 install --upgrade pip
> ```

I am using the latest as mentioned:
```
python3 -m pip --version
pip 22.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
```

The hashes were disabled due to an error that said something along the lines of if a single request has hashes, then all must have them. This did not appear to work with installing / specifying a dependency via something like `https://github.com/PlantandFoodResearch/machine-vision-acquisition.git/tarball/main`.

**Comment by velovix** [comment]
@nznobody I just added a new way of installing dependencies that uses Poetry's new bundle plugin as of v0.7.0. This avoids having to export dependencies to a `requirements.txt`. I think it will fix the hash issue for you, and it might affect the dist-packages/site-packages behavior you're observing as well. This requires Poetry `>=1.2.0`, the Bundle plugin, and the `--method bundle` flag when running the dependency installation script.

**Comment by nznobody** [comment]
> @nznobody I just added a new way of installing dependencies that uses Poetry's new bundle plugin as of v0.7.0. This avoids having to export dependencies to a `requirements.txt`. I think it will fix the hash issue for you, and it might affect the dist-packages/site-packages behavior you're observing as well. This requires Poetry `>=1.2.0`, the Bundle plugin, and the `--method bundle` flag when running the dependency installation script.

Thanks! I have sadly had to move to ROS1 for other reasons and so might not get around to testing this but will keep it in mind for my next ROS2 project!

**Comment by velovix** [comment]
Gotcha, well thank you for your interest in the project anyway! Is it okay if I close this PR for now, since a lot has changed since it work started on it?

**Comment by nznobody** [comment]
No worries, I hope to be back! Sure thing :)

**Pull request closed without merging**
