### PR TITLE
Add support for pure Python Poetry packages

### LINKED ISSUE #29: remove dependency on package.xml
This extension currently requires a `package.xml` to be present. Similar to how [`colcon-cmake`](https://github.com/colcon/colcon-cmake) and [`colcon-ros`](https://github.com/colcon/colcon-ros) work, I suggest that it would make a lot of sense to make this optional.

There could be a package `colcon-poetry` that extracts all information solely from the `pyproject.toml` and a `colcon-poetry-ros` that merges the information from the `pyproject.toml` and `package.xml`. This is useful in order to build "pure" python packages without a `package.xml` that only require python packages available on PyPI, and to have the option to define additional non-python dependencies in a `package.xml`.

### PR DESCRIPTION
**Pull request by velovix**
This allows Poetry packages to be installed by Colcon even if they aren't also ROS packages. This was an artificial limitation in the first place whose only purpose was to add some additional correctness checks for ROS packages.

Fixes #29

### CODE REVIEW

**Review by apockill — APPROVED** [review]

**Comment by christian-rauch** [comment]
Thanks. Generally, this seems to work. I only noticed that dependencies are not tracked.

When I call `colcon graph --dot > deps.dot` and look at the dependency graph via `xdot deps.dot` then all my packages are independent (there are no arrows connecting packages), although the section `[tool.poetry.dependencies]` lists one of the packages on the same workspace as a dependency.

**Comment by christian-rauch** [comment]
Scripts under `[tool.poetry.scripts]` are installed to `lib` and not `bin`. This is different from pip, where those are installed to `$HOME/.local/bin/`.

**Comment by velovix** [comment]
@christian-rauch Thanks for testing `colcon graph`, I'll try to take a look at that this week. The `lib` behavior is not new and is, as far as I'm aware, necessary for ROS to see the binaries. It's done [here](https://github.com/UrbanMachine/colcon-poetry-ros/blob/0316c8e2d988afab087a2afcccb0d05211aeb782/colcon_poetry_ros/task/poetry/build.py#L111).

**Comment by christian-rauch** [comment]
> The `lib` behavior is not new and is, as far as I'm aware, necessary for ROS to see the binaries. It's done [here](https://github.com/UrbanMachine/colcon-poetry-ros/blob/0316c8e2d988afab087a2afcccb0d05211aeb782/colcon_poetry_ros/task/poetry/build.py#L111).

At least with CMake packages, there is a differentiation between regular executables from plain CMake packages and nodes from ament packages. For example, https://github.com/AprilRobotics/apriltag is a plain CMake package, that will install the demo executables `apriltag_demo` and `opencv_demo` in the folder `install/apriltag/bin/`, such that they can be called just by sourcing the environment.

For ROS-specific binaries or nodes, I think it would make sense to rely on a dedicated section in `pyproject.toml` that lists the ROS nodes. Otherwise, the installed scripts should be handled just like standard python scripts and executables.

**Comment by apockill** [comment]
With the usual python/ROS workflow, they have you set up scripts in the `setup.py` as normal scripts, and those are just assumed to be ROS executables. I think mirroring that workflow with poetry might be more clear for the users of the tool.

**Comment by christian-rauch** [comment]
> With the usual python/ROS workflow, they have you set up scripts in the `setup.py` as normal scripts, and those are just assumed to be ROS executables.

I experimented a bit with the `setup.py` and [colcon-python-setup-py](https://github.com/colcon/colcon-python-setup-py) before and was able to install standard python packages including its executable. My plan with colcon-poetry-ros was to mirror this and poetry's behaviour by installing plain python packages alongside other colcon packages in the same way their native tools (cmake, poetry) would do.

> I think mirroring that workflow with poetry might be more clear for the users of the tool.

It's a good question of what the expected behaviour should be :-) I thought that there actually should be a `colcon-poetry` and a `colcon-poetry-ros` extension for plain and ROS Python packages. My expectation on a "poetry" extension is that it behaves like normal poetry, just in a colcon workspace. I haven't looked too deep into this, but I assume that for creating a Python ROS node/package, you will have to add additional steps, such as message generation or launch file installation, anyway. So it would make sense to support standard poetry behaviour as a baseline with `colcon-poetry` and extend this by anything specifically required by ROS nodes with `colcon-poetry-ros`.

**Comment by christian-rauch** [comment]
@velovix @apockill Are you interested in replicating the poetry behaviour where scripts and executables are installed in the `bin` folder?

**Comment by velovix** [comment]
Sorry for the delay on this Christian. You raise good points that require some thinking.

> I thought that there actually should be a colcon-poetry and a colcon-poetry-ros extension for plain and ROS Python packages

I agree with this on principle and it would allow the project to better mirror the way Colcon's official extensions are developed. In practice it has some unfortunate knock-on effects where we would need to maintain two separate packages and perhaps two repositories, although I suppose we could maintain them in the same repository. Maybe that's the future of this project, but it seems a bit heavy for now.

One reason why it feels "heavy" to me is because there's actually very little ROS stuff we need to do in this extension. We don't need to worry about message generation, because that needs to be done with CMake, and we don't need to worry about launch file installation because that's handled elsewhere in the build process.

> For ROS-specific binaries or nodes, I think it would make sense to rely on a dedicated section in pyproject.toml that lists the ROS nodes. Otherwise, the installed scripts should be handled just like standard python scripts and executables.

I tend to agree with @apockill that I would prefer to treat Poetry scripts and ROS nodes as equivalent to mirror Colcon's setup.py behavior and also because I think it's more intuitive. You have probably already noticed this, but the executables actually end up in both places. That seems to me like a good compromise, as it simultaneously fits Poetry's and ROS's expectations on where they should go.

**Comment by christian-rauch** [comment]
A gentle ping :-) Do you think this is ready?

**Comment by velovix** [comment]
Thank you for the reminder! I got sidetracked on this while trying to fix the dependency issue you identified. Unfortunately, it's still a problem, but I'll leave that for another PR since that's not a regression from these changes. I'm happy where this one is.

**Pull request merged**
